/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScorecardsRouteImport } from './routes/scorecards'
import { Route as OutingsRouteImport } from './routes/outings'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as GolfersRouteImport } from './routes/golfers'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScorecardsIdRouteImport } from './routes/scorecards_.$id'
import { Route as OutingsIdRouteImport } from './routes/outings_.$id'
import { Route as GolfersIdRouteImport } from './routes/golfers_.$id'
import { Route as CoursesCreateRouteImport } from './routes/courses_.create'
import { Route as CoursesIdRouteImport } from './routes/courses_.$id'

const ScorecardsRoute = ScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsRoute = OutingsRouteImport.update({
  id: '/outings',
  path: '/outings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfersRoute = GolfersRouteImport.update({
  id: '/golfers',
  path: '/golfers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardsIdRoute = ScorecardsIdRouteImport.update({
  id: '/scorecards_/$id',
  path: '/scorecards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsIdRoute = OutingsIdRouteImport.update({
  id: '/outings_/$id',
  path: '/outings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfersIdRoute = GolfersIdRouteImport.update({
  id: '/golfers_/$id',
  path: '/golfers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCreateRoute = CoursesCreateRouteImport.update({
  id: '/courses_/create',
  path: '/courses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses_/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/golfers': typeof GolfersRoute
  '/honors': typeof HonorsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/outings': typeof OutingsRoute
  '/scorecards': typeof ScorecardsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/create': typeof CoursesCreateRoute
  '/golfers/$id': typeof GolfersIdRoute
  '/outings/$id': typeof OutingsIdRoute
  '/scorecards/$id': typeof ScorecardsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/golfers': typeof GolfersRoute
  '/honors': typeof HonorsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/outings': typeof OutingsRoute
  '/scorecards': typeof ScorecardsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/create': typeof CoursesCreateRoute
  '/golfers/$id': typeof GolfersIdRoute
  '/outings/$id': typeof OutingsIdRoute
  '/scorecards/$id': typeof ScorecardsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/golfers': typeof GolfersRoute
  '/honors': typeof HonorsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/outings': typeof OutingsRoute
  '/scorecards': typeof ScorecardsRoute
  '/courses_/$id': typeof CoursesIdRoute
  '/courses_/create': typeof CoursesCreateRoute
  '/golfers_/$id': typeof GolfersIdRoute
  '/outings_/$id': typeof OutingsIdRoute
  '/scorecards_/$id': typeof ScorecardsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/courses'
    | '/enroll'
    | '/golfers'
    | '/honors'
    | '/login'
    | '/me'
    | '/outings'
    | '/scorecards'
    | '/courses/$id'
    | '/courses/create'
    | '/golfers/$id'
    | '/outings/$id'
    | '/scorecards/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/courses'
    | '/enroll'
    | '/golfers'
    | '/honors'
    | '/login'
    | '/me'
    | '/outings'
    | '/scorecards'
    | '/courses/$id'
    | '/courses/create'
    | '/golfers/$id'
    | '/outings/$id'
    | '/scorecards/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/courses'
    | '/enroll'
    | '/golfers'
    | '/honors'
    | '/login'
    | '/me'
    | '/outings'
    | '/scorecards'
    | '/courses_/$id'
    | '/courses_/create'
    | '/golfers_/$id'
    | '/outings_/$id'
    | '/scorecards_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  CoursesRoute: typeof CoursesRoute
  EnrollRoute: typeof EnrollRoute
  GolfersRoute: typeof GolfersRoute
  HonorsRoute: typeof HonorsRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  OutingsRoute: typeof OutingsRoute
  ScorecardsRoute: typeof ScorecardsRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesCreateRoute: typeof CoursesCreateRoute
  GolfersIdRoute: typeof GolfersIdRoute
  OutingsIdRoute: typeof OutingsIdRoute
  ScorecardsIdRoute: typeof ScorecardsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scorecards': {
      id: '/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof ScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings': {
      id: '/outings'
      path: '/outings'
      fullPath: '/outings'
      preLoaderRoute: typeof OutingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golfers': {
      id: '/golfers'
      path: '/golfers'
      fullPath: '/golfers'
      preLoaderRoute: typeof GolfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecards_/$id': {
      id: '/scorecards_/$id'
      path: '/scorecards/$id'
      fullPath: '/scorecards/$id'
      preLoaderRoute: typeof ScorecardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings_/$id': {
      id: '/outings_/$id'
      path: '/outings/$id'
      fullPath: '/outings/$id'
      preLoaderRoute: typeof OutingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golfers_/$id': {
      id: '/golfers_/$id'
      path: '/golfers/$id'
      fullPath: '/golfers/$id'
      preLoaderRoute: typeof GolfersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/create': {
      id: '/courses_/create'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof CoursesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$id': {
      id: '/courses_/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  CoursesRoute: CoursesRoute,
  EnrollRoute: EnrollRoute,
  GolfersRoute: GolfersRoute,
  HonorsRoute: HonorsRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  OutingsRoute: OutingsRoute,
  ScorecardsRoute: ScorecardsRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesCreateRoute: CoursesCreateRoute,
  GolfersIdRoute: GolfersIdRoute,
  OutingsIdRoute: OutingsIdRoute,
  ScorecardsIdRoute: ScorecardsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
